name: "Generate Release and Publish"
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    environment: webstores-publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3.3.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js 20.x LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Browser Platform Publisher
        uses: PlasmoHQ/bpp@v3.5.0
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
